

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS subtopics CASCADE;
DROP TABLE IF EXISTS links CASCADE;

-- Users table
CREATE TABLE users (
   id BIGSERIAL PRIMARY KEY,
   username VARCHAR(50) NOT NULL,
   email VARCHAR(100) UNIQUE NOT NULL,
   password VARCHAR(255) NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Subjects table
CREATE TABLE subjects (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Subtopics Table
CREATE TABLE subtopics (
   id BIGSERIAL PRIMARY KEY,
   subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
   name VARCHAR(100) NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Links Table
CREATE TABLE links (
   id BIGSERIAL PRIMARY KEY,
   subtopic_id BIGINT NOT NULL REFERENCES subtopics(id) ON DELETE CASCADE,
   title VARCHAR(150) NOT NULL,
   description TEXT,
   url TEXT NOT NULL,
   insertion_order INTEGER,
   date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);